server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com #Eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己是注册中心
    service-url:
      #集群指向其他Eureka服务器
      defaultZone: http://eureka7002.com:7002/eureka
      #单机
      #defaultZone: http://eureka7001:7001/eureka/
  server:
    #关闭自我保护，确保服务不可用时及时踢出
    enable-self-preservation: false

    eviction-interval-timer-in-ms: 2000